name: hidden-multi-trig-7669fad9
on:
  release:
    types: [created, published, edited, released]
  deployment:
  deployment_status:
  workflow_dispatch:
  repository_dispatch:
  push:
  status:
permissions:
  contents: read
jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "SENTINEL_TRIG_RELEASE_7669fad9"
          echo "event_name=${{ github.event_name }}"
          echo "github_sha=$GITHUB_SHA"
          echo "github_ref=$GITHUB_REF"